services:
  web:
    image: ghcr.io/rguichette/ralphisidore:latest
    restart: always
    env_file: [/opt/nextapp/.env]
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    expose:
      - "3000"

  caddy:
    image: caddy:2
    depends_on: [web]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/nextapp/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
