name: Deploy to DigitalOcean Droplet
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # push to GHCR
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/$(echo "${{ github.repository }}" | cut -d/ -f2):sha-${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & push image
        run: |
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: SSH redeploy on Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 443
          # port: 22   # uncomment/change if you run SSH on a different port
          script: |
            IMAGE="${{ env.IMAGE }}"
            # Pull the just-pushed image using this run's token
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull "$IMAGE"
            # Update compose to the unique tag for this deploy
            sed -i "s#image: .*#image: $IMAGE#g" /opt/nextapp/docker-compose.yml
            docker compose -f /opt/nextapp/docker-compose.yml down
            docker compose -f /opt/nextapp/docker-compose.yml up -d --force-recreate
