name: Deploy to DigitalOcean Droplet
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      # Build & push image to GHCR with :latest
      - name: Build and push image
        id: build
        run: |
          REPO_LC="$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')"
          IMAGE="ghcr.io/${REPO_LC}:latest"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "Using image: $IMAGE"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      # SSH into Droplet and redeploy
      - name: SSH redeploy on Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.DO_SSH_PORT }}
          envs: IMAGE
          script: |
            set -e
            cd /opt/nextapp/app   # repo clone path
            git fetch origin
            git reset --hard origin/main

            IMAGE="${{ steps.build.outputs.image }}"
            echo "Deploying $IMAGE"

            docker login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"
            docker pull "$IMAGE"
            docker compose up -d --force-recreate --remove-orphans
            docker image prune -f
