name: Deploy to DigitalOcean Droplet
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      # 1) Compute lowercase repo path (ghcr requires lowercase)
      - name: Compute image name
        id: meta
        run: |
          REPO_LC="ghcr.io/${GITHUB_REPOSITORY,,}"
          echo "repo_lc=$REPO_LC" >> "$GITHUB_OUTPUT"

      # 2) Build & push image to GHCR
      - name: Build and push image
        run: |
          IMAGE="${{ steps.meta.outputs.repo_lc }}:latest"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      # 3) SSH into the Droplet, pull repo + redeploy with updated compose
      - name: SSH redeploy on Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.DO_SSH_PORT }}
          script: |
            set -e
            APP_DIR=/opt/nextapp/app
            REPO="${{ github.repository }}"
            IMAGE="ghcr.io/${REPO,,}:latest"

            # Clone repo first time only
            if [ ! -d "$APP_DIR/.git" ]; then
              mkdir -p /opt/nextapp
              git clone "https://github.com/$REPO" "$APP_DIR"
            fi

            cd "$APP_DIR"
            git fetch origin
            git reset --hard origin/main

            # pull latest image and run compose from repo
            docker login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"
            docker pull "$IMAGE"
            docker compose up -d --force-recreate --remove-orphans
            docker image prune -f
